<?php

/**
 * @file
 * Implements the API through which Google Analytics data can be accessed.
 */

/**
 * Implements hook_help().
 */
function google_analytics_reports_api_help($path, $arg) {
  switch ($path) {
    case 'admin/help#google_analytics_reports_api':
      $output = '<p>' . t('Google Analytics Reports and it\'s API module provides site administrators and programmers a rich API to generate graphical reports based on Google Analytics data.  The reports module includes a helpful sitewide report located under <a href="!link">Drupal\'s default administrator reports</a>, and blocks for both sitewide and path-based reports.', array(
        '!link' => url('admin/reports'),
      )) . '</p>';
      $output .= '<p>' . t('Programmers can build complex queries against Google Analytics and display them in any format they like.  To get started coding your own reports, visit the <a href="!link">Google Analytics Reports documentation page on drupal.org</a>.', array(
        '!link' => url('https://www.drupal.org/node/1138274'),
      )) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function google_analytics_reports_api_menu() {
  $items['admin/config/system/google-analytics-reports-api'] = array(
    'title' => 'Google Analytics Reports API',
    'description' => 'Configure your account, profiles, and reports.',
    'page callback' => 'drupal_get_form',
    'file' => 'google_analytics_reports_api.pages.inc',
    'page arguments' => array('google_analytics_reports_api_admin'),
    'access arguments' => array('administer google analytics reports api'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function google_analytics_reports_api_permission() {
  return array(
    'administer google analytics reports api' => array(
      'title' => t('administer google analytics reports api'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function google_analytics_reports_api_theme() {
  return array(
    'google_analytics_reports_api_profile_label' => array(
      'arguments' => array(
        'profile' => NULL,
      ),
    ),
  );
}

/**
 * Instantiate a new GoogleAnalyticsReportsApiFeed object.
 *
 * @return object
 *   GoogleAnalyticsReportsApiFeed object to authorize access and request data
 *   from the Google Analytics Core Reporting API.
 */
function google_analytics_reports_api_new_gafeed() {
  module_load_include('inc', 'google_analytics_reports_api', 'google_analytics_reports_api.lib');
  if (variable_get('google_analytics_reports_api_access_token', NULL) && time() < variable_get('google_analytics_reports_api_expires_at', NULL)) {
    // If the access token is still valid, return an authenticated GAFeed
    return new GoogleAnalyticsReportsApiFeed(variable_get('google_analytics_reports_api_access_token', NULL));
  }
  else if (variable_get('google_analytics_reports_api_refresh_token', NULL)) {
    // If the site has an access token and refresh token, but the access
    // token has expired, authenticate the user with the refresh token 
    $client_id = variable_get('google_analytics_reports_client_id', NULL);
    $client_secret = variable_get('google_analytics_reports_client_secret', NULL);
    $refresh_token = variable_get('google_analytics_reports_api_refresh_token', NULL);

    try {
      $GAFeed = new GoogleAnalyticsReportsApiFeed();
      $GAFeed -> refreshToken($client_id, $client_secret, $refresh_token);

      variable_set("google_analytics_reports_api_access_token", $GAFeed->access_token);
      variable_set("google_analytics_reports_api_expires_at", $GAFeed->expires_at);
      return $GAFeed;
    }
    catch (Exception $e) {
      drupal_set_message(t("There was an authentication error. Message: " . $e->getMessage()), 'error', FALSE);
      return NULL;
    }
  }
  else if (isset($_GET['code'])) {
    // If there is no access token or refresh token and client is returned
    // to the config page with an access code, complete the authentication
    $client_id = variable_get('google_analytics_reports_client_id', NULL);
    $client_secret = variable_get('google_analytics_reports_client_secret', NULL);
    $redirect_uri = variable_get('google_analytics_reports_redirect_uri', NULL);

    try {
      $GAFeed = new GoogleAnalyticsReportsApiFeed();
      $GAFeed -> finishAuthentication($client_id, $client_secret, $redirect_uri);

      variable_set('google_analytics_reports_api_access_token', $GAFeed->access_token);
      variable_set('google_analytics_reports_api_expires_at', $GAFeed->expires_at);
      variable_set('google_analytics_reports_api_refresh_token', $GAFeed->refresh_token);
      variable_del('google_analytics_reports_redirect_uri');

      drupal_set_message(t("You have been successfully authenticated."), 'status', FALSE);
      drupal_goto($redirect_uri);
    }
    catch (Exception $e) {
      drupal_set_message(t("There was an authentication error. Message: " . $e->getMessage()), 'error', FALSE);
      return NULL;
    }
  }
  else {
    return NULL;
  }
}

/**
 * Request report data.
 *
 * @param array $params
 *   An associative array containing:
 *   - profile_id: required
 *    [default=variable_get('google_analytics_reports_api_profile_id')].
 *   - metrics: required.
 *   - dimensions: optional [default=none].
 *   - sort_metric: optional [default=none].
 *   - filters: optional [default=none].
 *   - segment: optional [default=none].
 *   - start_date: optional [default=2005-01-01].
 *   - end_date: optional [default=today].
 *   - start_index: optional [default=1].
 *   - max_results: optional [default=10,000].
 * @param array $cache_options
 *   An optional associative array containing:
 *   - cid: optional [default=md5 hash].
 *   - expire: optional [default=CACHE_TEMPORARY].
 *   - refresh: optional [default=FALSE].
 *
 * @return object
 *   GoogleAnalyticsReportsApiFeed object to authorize access and request data
 *   from the Google Analytics Core Reporting API after reporting data.
 */
function google_analytics_reports_api_report_data($params = array(), $cache_options = array()) {
  if(isset($params['profile_id'])) {
    $params['profile_id'] = 'ga:' .$params['profile_id'];
  } else {
    $params['profile_id'] = 'ga:' . variable_get('google_analytics_reports_api_profile_id', 0);
  }

  $ga_feed = google_analytics_reports_api_new_gafeed();

  if ($ga_feed) {
    $ga_feed->queryReportFeed($params, $cache_options);
    return $ga_feed;
  }
  else {
    drupal_set_message(t("There was an authentication error. Please check your Google API settings and try again."), 'error', FALSE);
    $error = array('error' => TRUE);
    return $error;
  }
}

/**
 * Programmatically revoke token.
 */
function google_analytics_reports_api_revoke() {
  $ga_feed = google_analytics_reports_api_new_gafeed();
  $ga_feed->revokeToken();
  // Delete module variables.
  db_delete('variable')
    ->condition('name', 'google_analytics_reports_api_%', 'LIKE')
    ->execute();
}

/**
 * Sets the expiry timestamp for cached queries.
 *
 * Default is 3 days.
 *
 * @return int
 *   The UNIX timestamp to expire the query at.
 */
function google_analytics_reports_api_cache_time() {
  return time() + variable_get('google_analytics_reports_api_cache_length', 259200);
}

/**
 * Returns HTML for the full string label of profiles.
 *
 * @param array $variables
 *   An associative array containing:
 *   - profile: Google Analytics profile object.
 *
 * @ingroup themeable
 */
function theme_google_analytics_reports_api_profile_label($variables) {
  return $variables['profile']->name . ' (' . $variables['profile']->id . ')';
}

/**
 * Implements hook_domain_conf().
 */
function google_analytics_reports_api_domain_conf() {
  $profile_id = variable_get('google_analytics_reports_api_profile_id', 0);
  $form['google_analytics_reports_api'] = array(
    '#type' => 'fieldset',
    '#title' => t('Google Analytics Reports API'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  if ($profile_id) {
    $admin_form = google_analytics_reports_api_admin();
    $form['google_analytics_reports_api']['google_analytics_reports_api_profile_id'] = $admin_form['ga']['google_analytics_reports_api_profile_id'];
    $form['google_analytics_reports_api']['google_analytics_reports_api_profile_id']['#description'] = t('Choose your Google Analytics profile.');
  }
  else {
    $form['google_analytics_reports_api']['authorize']['#markup'] = '<p>' . t('You must <a href="!url">authorize</a> Drupal to use your Analytics account before you can view reports.', array('!url' => url('admin/config/system/google-analytics-reports-api'))) . '</p>';
  }
  return $form;
}
