<?php
/**
 * @file
 * Installation file for Google Analytics API module.
 */

/**
 * Implements hook_uninstall().
 */
function google_analytics_api_uninstall() {
  variable_del('google_analytics_reports_hd');
  variable_del('google_analytics_reports_oauth_token');
  variable_del('google_analytics_reports_oauth_token_secret');
  variable_del('google_analytics_reports_profile_id');
  variable_del('google_analytics_reports_cache_length');
}
