<?php

/**
 * @file
 * Front-end interfaces that use the Google Analytics Reports API module.
 */

/**
 * Implements hook_menu().
 */
function google_analytics_reports_menu() {
  $items['admin/reports/google-analytics/detail'] = array(
    'title' => 'Content Detail',
    'page callback' => 'google_analytics_reports_detail_page',
    'access arguments' => array('access google analytics reports'),
    'file' => 'google_analytics_reports.pages.inc',
    'type' => MENU_CALLBACK,
  );
  $items['google-analytics-reports/ajax/path-mini'] = array(
    'title' => 'Page traffic',
    'page callback' => 'google_analytics_reports_path_mini_ajax',
    'access arguments' => array('access google analytics reports'),
    'file' => 'google_analytics_reports.blocks.inc',
    'type' => MENU_CALLBACK,
  );
  $items['google-analytics-reports/ajax/dashboard'] = array(
    'title' => 'Page traffic',
    'page callback' => 'google_analytics_reports_dashboard_ajax',
    'access arguments' => array('access google analytics reports'),
    'file' => 'google_analytics_reports.blocks.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_page_build().
 */
function google_analytics_reports_page_build(&$page) {
  drupal_add_js(
    array(
      'googleAnalyticsReportsAjaxUrl' => url('google-analytics-reports/ajax'),
    ),
    'setting'
  );
}

/**
 * Implements hook_block_info().
 */
function google_analytics_reports_block_info() {
  $blocks['path_mini']['info'] = t('Google Analytics page traffic');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function google_analytics_reports_block_view($delta = '') {
  if (!user_access('access google analytics reports')) {
    return FALSE;
  }
  switch ($delta) {
    case 'path_mini':
      $block['subject'] = t('Page traffic');
      $block['content'] = '<div class="google-analytics-reports-path-mini"></div>';
      return $block;
  }
}

/**
 * Implements hook_permission().
 */
function google_analytics_reports_permission() {
  return array(
    'access google analytics reports' => array(
      'title' => t('access google analytics reports'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function google_analytics_reports_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_theme().
 */
function google_analytics_reports_theme() {
  return array(
    'google_analytics_reports_detail' => array(
      'variables' => array('report' => NULL),
      'template' => 'templates/google_analytics_reports_detail',
      'file' => 'google_analytics_reports.theme.inc',
    ),
    'google_analytics_reports_path_mini' => array(
      'variables' => array('report' => NULL),
      'file' => 'google_analytics_reports.theme.inc',
    ),
  );
}

/**
 * Construct a filter string.
 *
 * That grabs pagePaths corresponding to the specified path.
 *
 * @param string $path
 *   Page path.
 *
 * @return string
 *   Google Analytics API page filter.
 */
function _google_analytics_reports_path_filter($path) {
  // Decode urls, that might appear due to browsers particularities.
  $path = urldecode($path);

  // Google Analytics regex filters have a limit of 32 characters. Therefore we
  // can't simply create one filter per pagePath. Instead we are going too do a
  // "contains substring" match on the path, and then take as many of the ending
  // characters paired with ([?#].*)?$.

  // Use 100 character maximum to allow some room for escaping regex
  // metacharacters.
  if (strlen($path) <= 121) {
    $filter = 'ga:pagePath=~^' . preg_quote($path) . '(#.*)?$';
  }
  else {
    $filter = 'ga:pagePath=@' . $path . ';ga:pagePath=~' . preg_quote(substr($path, -100)) . '(#.*)?$';
  }
  return $filter;
}

/**
 * Helper function to generate an error message.
 *
 * @return string
 *   Error message.
 */
function _google_analytics_reports_error_message() {
  $message = t('There was a problem retrieving the statistics.');
  if (user_access('access site reports') && user_access('access administration pages') && module_exists('dblog')) {
    $message .= ' ' . t('Please review the <a href="!url">watchdog</a> for details.', array('!url' => url('admin/reports/dblog')));
  }
  return $message;
}
