<?php
/**
 * @file
 * A light-weight, customizable image gallery plugin for Drupal based on jQuery
 */

/**
 * Implements hook_library().
 * @author minorOffense <mwinstone@coldfrontlabs.ca>
 */
function flexslider_library() {
  $libraries['flexslider'] = array(
    'title' => 'FlexSlider',
    'website' => 'http://flex.madebymufffin.com/',
    'version' => '1.8',
    'js' => array(
      libraries_get_path('flexslider') . '/jquery.flexslider-min.js' => array(),
    ),
    'css' => array(
      libraries_get_path('flexslider') . '/flexslider.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_library_alter().
 * @author minorOffense <mwinstone@coldfrontlabs.ca>
 */
function flexslider_library_alter(&$libraries, $module) {
  $debug = variable_get('flexslider_debug', FALSE);
  if ($debug) {
    // Switch to the unminified version of the library
    if ($module == 'flexslider' && isset($libraries['flexslider'])) {
        $libraries['flexslider']['js'] = array(
          libraries_get_path('flexslider') . '/jquery.flexslider.js' => array(),
        );
    }
  }
  
  // @todo configure the styles for the theme to be altered by admin configurations

  // As it's only possible to use one theme per page, use the first one we get for everything.
  // @todo load the selected theme
  // @todo override css path
  $theme = (!empty($optionset['theme'])) ? $optionset['theme'] : 'default';
}

/**
 * Implements hook_permission().
 * @author minorOffense <mwinstone@coldfrontlabs.ca>
 */
function flexslider_permission() {
  return array(
    'administer flexslider' =>  array(
      'title' => t('Administer the FlexSlider module'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function flexslider_menu() {
  $items = array();

  $items['admin/config/media/flexslider'] = array(
    'title' => 'flexslider',
    'description' => 'Configure flexslider galleries.',
    'page callback' => 'flexslider_page_optionset_list',
    'access arguments' => array('administer flexslider'),
    'file' => 'flexslider.admin.inc',
  );
  $items['admin/config/media/flexslider/list'] = array(
    'title' => 'Option sets',
    'description' => 'List the current flexslider option sets.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/config/media/flexslider/add'] = array(
    'title' => 'Add option set',
    'description' => 'Add a new flexslider option set.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flexslider_form_optionset_add'),
    'access arguments' => array('administer flexslider'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 1,
    'file' => 'flexslider.admin.inc',
  );
  $items['admin/config/media/flexslider/edit/%flexslider_optionset'] = array(
    'title' => 'Edit option set',
    'description' => 'Configure an option set.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flexslider_form_optionset_edit', 5),
    'access arguments' => array('administer flexslider'),
    'file' => 'flexslider.admin.inc',
  );
  $items['admin/config/media/flexslider/delete/%flexslider_optionset'] = array(
    'title' => 'Delete option set',
    'description' => 'Delete an option set.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flexslider_optionset_form_delete', 5),
    'access arguments' => array('administer flexslider'),
    'file' => 'flexslider.admin.inc',
  );
  $items['admin/config/media/flexslider/advanced'] = array(
    'title' => 'Advanced settings',
    'description' => 'Configure the advanced flexslider module settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flexslider_form_settings'),
    'access arguments' => array('administer flexslider'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
    'file' => 'flexslider.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function flexslider_help($path, $arg) {
  switch ($path) {
    case 'admin/config/media/flexslider/edit/%':
      return
          '<p>'
        . t('An <em>option set</em> defines exactly how a flexslider image gallery looks like on your site. '
          . 'It is s a combination of <a href="@styles">image styles</a> for the various image sizes, flexslider theme and options.', array('@styles' => url('admin/config/media/image-styles'))). '<br />'
        . t('For a full documentation of all options, refer to the official <a href="@docs">flexslider documentation</a>.', array('@docs' => url('http://flex.madebymufffin.com/')))
        . '</p>';

    case 'admin/config/media/flexslider/advanced':
      return '<p>' . t('This page lists some automatically detected files and folders. To improve performance, they are cached until the files get deleted.<br />'
                   . 'If the module behaves strangely, try to clear the cached values below.') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function flexslider_theme() {
  return array(
   'flexslider_container' => array(
      'variables' => array('items' => array(), 'settings' => array()),
      'template' => 'theme/flexslider-container',
      'file' => 'theme/theme.inc',
    ),
    'flexslider_form_table' => array(
      'render element' => 'form',
      'file' => 'flexslider.admin.inc',
    ),
  );
}

/**
 * Implements hook_image_default_styles().
 */
function flexslider_image_default_styles() {
  $styles = array();

  // Default image preset for FlexSlider
  $styles['flexslider_full'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 960, 'height' => '', 'upscale' => TRUE),
        'weight' => 0,
      ),
    )
  );

  return $styles;
}

/**
 * Fetches all option sets from the database and returns them as an associative array.
 */
function flexslider_optionsets() {
  $optionsets = db_query("SELECT * FROM {flexslider_optionset}")->fetchAllAssoc('name', PDO::FETCH_ASSOC);
  foreach ($optionsets as &$optionset) {
    $optionset['options'] = empty($optionset['options']) ? array() : unserialize($optionset['options']);
  }
  return $optionsets;
}

/**
 * Fetches the given option set and returns it as an associative array or FALSE, if no set could be found.
 */
function flexslider_optionset_load($optionset_name) {
  $optionset = db_query("SELECT * FROM {flexslider_optionset} WHERE name = :name", array(':name' => $optionset_name))->fetchAssoc();
  if ($optionset !== FALSE) {
    $optionset['options'] = empty($optionset['options']) ? array() : unserialize($optionset['options']);
  }
  return $optionset;
}

/**
 * Checks whether an option set with the given name already exists.
 */
function flexslider_optionset_exists($optionset_name) {
  return (flexslider_optionset_load($optionset_name) !== FALSE);
}

/**
 * Saves the given option set to the database.
 * Set the $new flag if this set has not been written before.
 */
function flexslider_optionset_save($optionset, $new = FALSE) {
  $optionset += array(
    'title' => $optionset['name'],
    'options' => array(),
  );

  if ($new) {
    drupal_write_record('flexslider_optionset', $optionset);
  }
  else {
    drupal_write_record('flexslider_optionset', $optionset, 'name');
  }
  return $optionset;
}

/**
 * Deletes the given option set from the database.
 */
function flexslider_optionset_delete($optionset) {
  db_delete('flexslider_optionset')->condition('name', $optionset['name'])->execute();
  // TODO: update formatters?
  return TRUE;
}

/**
 * Searches for available themes inside the flexslider folder.
 * The list of themes
 */
function flexslider_get_themes($nocache = FALSE) {
  if (!$nocache && (($themes = cache_get('flexslider_themes')) !== FALSE))
    return $themes->data;

  $themes = array();

  // Search for theme folders
  $path = libraries_get_path('flexslider') . '/themes/';
  
  if (is_dir($path) && (($path_handle = opendir($path)) !== FALSE)) {
    while (($theme = readdir($path_handle)) !== FALSE) {
     
      if (!is_dir($path . $theme) || $theme[0] == '.')
        continue;

      // Search for the theme JavaScript file, minified version first
      $css = glob($path . $theme . '/*.css');

      // Sort by filename to (hopefully) get the newest version.
      if (count($css) > 0) {
        rsort($css);
        $themes[$theme] = $css[0];
      }
    }
    closedir($path_handle);

    cache_set('flexslider_themes', $themes);
  }

  return $themes;
}

/*
 * This function loads the required JavaScripts and settings for a flexslider
 * instance.
 */
function flexslider_add($id, $optionset) {
  // Static array to remember which scripts are already attached.
  // @todo not currently in use
  $cache = &drupal_static(__FUNCTION__, array());

  // @todo investigate the best way to cache data loaded from drupal_add_library()
  drupal_add_library('flexslider', 'flexslider');

  // Moved theme configuration into hook_library_alter().

  // JavaScript settings
  $js_settings = array(
    //'themepath' => file_create_url($cache['theme']),
    'optionsets' => array(
      $optionset['name'] => $optionset['options'],
    ),
    'instances' => array(
      'flexslider-' . $id => $optionset['name'],
    ),
  );

  drupal_add_js(array('flexslider' => $js_settings), 'setting');
  
  // Loader JavaScript
  drupal_add_js(drupal_get_path('module', 'flexslider') . '/assets/js/flexslider.load.js');
}