<!-- Frequently Asked Questions -->
<div class="span4 front-module">
  <h4 class="module-title">Frequently Asked Questions</h4>

  <div class="module-content">
    <div class="faq-image">
      <a href="http://www.soc.ucsb.edu/sexinfo/question/faq-how-do-i-increase-sexual-arousal">
      <img class="" src="<?php print path_to_theme() . '/images/modules/' . 'arousal.jpg'; ?>" />
      <div class="caption-slide">
        <h3>How Do I Increase Sexual Arousal?</h3></a>
        <p>There are many ways to increase your and your partner’s sexual arousal. Sexual arousal is... <a href="http://www.soc.ucsb.edu/sexinfo/question/faq-how-do-i-increase-sexual-arousal">Read More &gt;</a>
        </p>
      </div>
    </div>
  </div>
</div>


<!-- Topic Tag Cloud -->
<!-- begin tag cloud : generated by TagCrowd.com
Feel free to modify as long as you keep this notice.

This code and its rendered image are released under the Creative Commons Attribution-Noncommercial 3.0 Unported License. (http://creativecommons.org/licenses/by-nc/3.0/)

For COMMERCIAL USE LICENSING, visit http://tagcrowd.com/licensing.html
-->
<div class="span4 front-module">
  <h4 class="module-title">Choose a Topic to Learn About</h4>

<div id="htmltagcloud"> <span id="0" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/anal-sex">anal</a></span> <span id="6" class="wrd tagcloud5"><a href="http://www.soc.ucsb.edu/sexinfo/article/male-condom">condom</a></span> <span id="10" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/semen">ejaculate</a></span> <span id="19" class="wrd tagcloud6"><a href="http://www.soc.ucsb.edu/sexinfo/article/hymen">hymen</a></span> <span id="20" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/article/sti-symptom-chart">infections</a></span> <span id="23" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/category/body">body</a></span> <span id="24" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/taxonomy/term/447/all">violence</a></span> <span id="23" class="wrd tagcloud5"><a href="http://www.soc.ucsb.edu/sexinfo/category/love-relationships/love">love</a></span> <span id="26" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/category/sexual-activity/masturbation">masturbation</a></span> <span id="28" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/sexpert-approved-sex-positions">positions</a></span> <span id="32" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/question/faq-common-questions-about-penis">penis</a></span> <span id="36" class="wrd tagcloud6"><a href="http://www.soc.ucsb.edu/sexinfo/questions/pregnancy">pregnancy</a></span> <span id="39" class="wrd tagcloud8"><a href="http://www.soc.ucsb.edu/sexinfo/category/sexual-activity/spice-your-sex-life">sex</a></span> <span id="42" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/category/contraception/barrier-methods">protection</a></span> <span id="43" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/article/overview-female-reproductive-system">vagina</a></span> <span id="3" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/effective-communication">communication</a></span> <span id="0" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/article/overview">abortion</a></span> </div>

</div>

<!-- Quizzes -->
<div class="span4 front-module">
  <h4 class="module-title">Test Your Knowledge</h4>

  <div class="module-content ask-module">
    <p>Do you think you know it all? Are you an expert on masturbation, LGBTQ facts, paraphilias, or pregnancy and abortion? Quiz yourself <a href="<?php print $base_path . "quizzes" ?>">here</a> to see if you really are.</p>
$handler = new stdClass();
$handler->disabled = FALSE; /* Edit this to true to make a default handler disabled initially */
$handler->api_version = 1;
$handler->name = 'page_test_your_knowledge_panel_context';
$handler->task = 'page';
$handler->subtask = 'test_your_knowledge';
$handler->handler = 'panel_context';
$handler->weight = 0;
$handler->conf = array(
  'title' => 'Panel',
  'no_blocks' => 0,
  'pipeline' => 'standard',
  'body_classes_to_remove' => '',
  'body_classes_to_add' => '',
  'css_id' => '',
  'css' => '',
  'contexts' => array(),
  'relationships' => array(),
);
$display = new panels_display();
$display->layout = 'onecol';
$display->layout_settings = array();
$display->panel_settings = array(
  'style_settings' => array(
    'default' => NULL,
    'middle' => NULL,
  ),
);
$display->cache = array();
$display->title = 'Test Your Knowledge';
$display->content = array();
$display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-1';
  $pane->panel = 'middle';
  $pane->type = 'node';
  $pane->subtype = 'node';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'nid' => '513',
    'links' => 0,
    'leave_node_title' => 0,
    'identifier' => '',
    'build_mode' => 'teaser',
    'link_node_title' => 0,
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = array();
  $display->content['new-1'] = $pane;
  $display->panels['middle'][0] = 'new-1';
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = 'new-1';
$handler->conf['display'] = $display;
  </div>

  <div class="module-footer">
    <a href="<?php print $base_path . "quizzes" ?>">Take a quiz &raquo;</a>
  </div>
</div>
