<div class="third front-module">
  <h3>Frequently Asked Questions</h3>
  <!--<p>Lorem ipsum dolor sit amet, lorem ipsum.</p>-->

  <div class="module-content">
    <div class="faq-image">
      <a href="http://www.soc.ucsb.edu/sexinfo/question/faq-how-do-i-increase-sexual-arousal">
      <div style="background: url('<?php print path_to_theme() . '/images/modules/' . 'arousal.jpg'; ?>')" class="faq-image-box"></div>

      <div class="caption-slide">
        <h3>How Do I Increase Sexual Arousal?</h3></a>
        <p>There are many ways to increase your and your partner’s sexual arousal. Sexual arousal is... <a href="http://www.soc.ucsb.edu/sexinfo/question/faq-how-do-i-increase-sexual-arousal">Read More &gt;</a>
        </p>
      </div>
    </div>
  </div>

</div>


<div class="third front-module">
  <h3>Explore our Topics</h3>
  <p style="font-size: 1.4em; line-height: 1.3;">
    We've completely redone our topics page to make it easier to find what you're looking for.
    <a href="#">Take a look &raquo;</a>
  </p>
</div>


<div class="third front-module">
  <h3>Test Your Knowledge</h3>
  <p>Do you think you know it all?</p>
  <p>Are you an expert on masturbation, LGBTQ facts, paraphilias, or pregnancy and abortion?</p>
  <p>Quiz yourself <a href="http://www.soc.ucsb.edu/sexinfo/quizzes">here</a> to see if you really are.</p>

  <a class="pink-block-btn" href="#">Take the quiz</a>
</div>


<?php
/*
<!-- Frequently Asked Questions -->
<div class="span4 front-module">
  <h4 class="module-title">Frequently Asked Questions</h4>

  <div class="module-content">
    <div class="faq-image">
      <a href="http://www.soc.ucsb.edu/sexinfo/question/faq-how-do-i-increase-sexual-arousal">
      <img class="" src="<?php print path_to_theme() . '/images/modules/' . 'arousal.jpg'; ?>" />
      <div class="caption-slide">
        <h3>How Do I Increase Sexual Arousal?</h3></a>
        <p>There are many ways to increase your and your partner’s sexual arousal. Sexual arousal is... <a href="http://www.soc.ucsb.edu/sexinfo/question/faq-how-do-i-increase-sexual-arousal">Read More &gt;</a>
        </p>
      </div>
    </div>
  </div>
</div>


<!-- Topic Tag Cloud -->
<!-- begin tag cloud : generated by TagCrowd.com
Feel free to modify as long as you keep this notice.

This code and its rendered image are released under the Creative Commons Attribution-Noncommercial 3.0 Unported License. (http://creativecommons.org/licenses/by-nc/3.0/)

For COMMERCIAL USE LICENSING, visit http://tagcrowd.com/licensing.html
-->
<div class="span4 front-module">
  <h4 class="module-title">Choose a Topic to Learn About</h4>

<div id="htmltagcloud"> <span id="0" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/anal-sex">anal</a></span> <span id="6" class="wrd tagcloud5"><a href="http://www.soc.ucsb.edu/sexinfo/article/male-condom">condom</a></span> <span id="10" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/semen">ejaculate</a></span> <span id="19" class="wrd tagcloud6"><a href="http://www.soc.ucsb.edu/sexinfo/article/hymen">hymen</a></span> <span id="20" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/article/sti-symptom-chart">infections</a></span> <span id="23" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/category/body">body</a></span> <span id="24" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/taxonomy/term/447/all">violence</a></span> <span id="23" class="wrd tagcloud5"><a href="http://www.soc.ucsb.edu/sexinfo/category/love-relationships/love">love</a></span> <span id="26" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/category/sexual-activity/masturbation">masturbation</a></span> <span id="28" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/sexpert-approved-sex-positions">positions</a></span> <span id="32" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/question/faq-common-questions-about-penis">penis</a></span> <span id="36" class="wrd tagcloud6"><a href="http://www.soc.ucsb.edu/sexinfo/questions/pregnancy">pregnancy</a></span> <span id="39" class="wrd tagcloud8"><a href="http://www.soc.ucsb.edu/sexinfo/category/sexual-activity/spice-your-sex-life">sex</a></span> <span id="42" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/category/contraception/barrier-methods">protection</a></span> <span id="43" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/article/overview-female-reproductive-system">vagina</a></span> <span id="3" class="wrd tagcloud1"><a href="http://www.soc.ucsb.edu/sexinfo/article/effective-communication">communication</a></span> <span id="0" class="wrd tagcloud3"><a href="http://www.soc.ucsb.edu/sexinfo/article/overview">abortion</a></span> </div>

</div>

<!-- Quizzes -->
<div class="span4 front-module">
  <h4 class="module-title">Test Your Knowledge</h4>

  <div class="module-content ask-module">
    <p>Do you think you know it all? Are you an expert on masturbation, LGBTQ facts, paraphilias, or pregnancy and abortion? Quiz yourself <a href="<?php print $base_path . "quizzes" ?>">here</a> to see if you really are.</p>
  </div>

  <div class="module-footer">
    <a href="<?php print $base_path . "quizzes" ?>">Take a quiz &raquo;</a>
  </div>
  </div>

 */
?>
